# Generated by Django 4.1 on 2022-09-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotspotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=50)),
                ('show_img', models.ImageField(default='show.jpg', upload_to='showcase')),
            ],
            options={
                'verbose_name': 'Showcase',
                'verbose_name_plural': 'Showcases',
                'db_table': 'showcase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lagos', models.BooleanField(default=False)),
                ('abuja', models.BooleanField(default=False)),
                ('owerri', models.BooleanField(default=False)),
                ('enugu', models.BooleanField(default=False)),
                ('ibadan', models.BooleanField(default=False)),
                ('portharcourt', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='pix.png', null=True, upload_to='space')),
                ('details', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspotapp.location')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotel',
                'managed': True,
            },
        ),
    ]
